version: '3'
services:
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pg-data:/var/lib/postgresql/data
      - ./data/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./data/data.sql:/docker-entrypoint-initdb.d/2-init.sql
    restart: always
  categoryService:
    image: vladsmirn289/category_service_rest
    container_name: serviceService
    ports:
      - 8084:8084
    environment:
      POSTGRES_HOST: db
    restart: always
    links:
      - db